Incorporate use off PPP package
DataKind-DC/CARES pull request #45
Opened 2020-09-14 19:18 UTC by kbmorales

Addresses the following issues:

#42 
#43 
#21 
#19 

Created an R package using code in this repo by @JohnMcCambridge and myself to download PPP data and make one clean unified PPP data set for analysis (for R users).

The package also incorporates an improved NAICS matching that iterates through subsequently older versions of NAICS index files from the US Census website.

This PR makes a script in`bin/setup.R` that will install the package and run the main assembly function in that package.

2020-09-16 13:13 UTC, JohnMcCambridge requested changes
see comment on setup.R

2020-09-16 13:13 UTC, JohnMcCambridge commented on bin/setup.R
> +ppp_df = PPP::ppp_assemble()
Got the following error (see last line). I suspect this is a relative directory issue? I just opened the .R file from the /bin directory. It created a dir in /bin (/bin/data_raw/naics) as well as in /CARES (/CARES/data-raw/All Data by State). My WD is: 
```
> getwd()
[1] "C:/Users/John/Dropbox/GitHub/DataKind-DC/CARES/bin"
```
 which got set as such because I just opened the .R file directly (and so it takes the directory of the file as WD).

As a side note, the warning "WARNING: Rtools is required to build R packages, but is not currently installed." doesn't cause any issues, I believe that is because Rtools is only needed if there is C or other compilable code, right? Might be good to add a little message reassuring people they don't need to worry?


```
> ### Assembles PPP data for further analysis
> ### kbmorales@protonmail.com
> 
> # For R users
> 
> if (!require(devtools)) install.packages('devtools')
Loading required package: devtools
Loading required package: usethis
> devtools::install_github("kbmorales/PPP")
WARNING: Rtools is required to build R packages, but is not currently installed.

Please download and install Rtools 4.0 from https://cran.r-project.org/bin/windows/Rtools/.
Skipping install of 'PPP' from a github remote, the SHA1 (01f1fc46) has not changed since last install.
  Use `force = TRUE` to force installation
> # Note: this script will download over 600MB of data into a 'data-raw'
> # folder in your home directory.
> 
> # It will prompt you which version of the data you'd like to use:
> # 1 is the latest data release: 2020-08-08
> # 2 is the first data release: 2020-07-06
> 
> ppp_df = PPP::ppp_assemble()
This function will assemble a finalized PPP dataset.
Which version of the PPP data would you like to ingest? 

1: Most recent (2020-08-08)
2: First release (2020-07-06?)

Selection: 2
This will save data to ~/data-raw/All Data by State
It will download over 100 MB of files.
Once unzipped, over 600 MB of disk space will be used.
Any existing files will be overwritten.
Proceed? 

1: Yes
2: Cancel

Selection: 1
trying URL 'https://sba.app.box.com/index.php?rm=box_download_shared_file&shared_name=tvb0v5i57oa8gc6b5dcm9cyw7y2ms6pp&file_id=f_687644633952'
Content type 'application/zip' length 105645322 bytes (100.8 MB)
downloaded 100.8 MB

Download complete.
Unzipping...
Creating path ./data-raw/
Unzip complete.
Downloading NAICS index files from US Census...
Creating path ./data-raw/naics/
Error in download.file(naics_urls[i], here::here("data-raw/naics", paste0("naics_",  : 
  cannot open destfile 'C:/Users/John/Dropbox/GitHub/DataKind-DC/CARES/data-raw/naics/naics_2017.xlsx', reason 'No such file or directory'
```

2020-09-16 14:06 UTC, kbmorales commented on bin/setup.R
> +ppp_df = PPP::ppp_assemble()
Good catch. A helper function I made to create directories was the culprit--I incorporated `here::here()` into it as well to hopefully avoid this in the future. Can you reinstall the package and try again?

Re: Rtools, that will pop up the first time you use a `devtools` function, and yup you're right it just compiles R packages from source. Added a comment to `bin/setup.R` that let's people know.

2020-09-16 14:07 UTC, kbmorales commented
Hey John just pushed changes to the `ppp` package that should resolve the wd issue. Can you test it out again and let me know if that works?

2020-09-17 12:49 UTC, JohnMcCambridge commented
retested, seems to be working well, perhaps some edge case issues we can continue to look at, but attempts at replication have failed.

2020-09-17 12:50 UTC, merged